# Generated by Django 4.2.2 on 2023-06-27 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='pseudo',
            field=models.CharField(default='pseudo', max_length=10),
            preserve_default=False,
        ),
    ]
