# Generated by Django 4.2.2 on 2023-06-27 12:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_remove_user_pseudo_user_last_login_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='profil_picture',
        ),
    ]
