# Generated by Django 4.2.2 on 2023-06-27 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_user_managers_user_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(default='user_9d10baa0-1913-429a-8d56-2ba4b9341977', max_length=50, unique=True),
        ),
    ]
