# Generated by Django 4.2.2 on 2023-06-27 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_alter_user_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(default='user_78d94b63-34dd-42a8-ac71-db74477995e6', max_length=50, unique=True),
        ),
    ]
