# Generated by Django 4.2.2 on 2023-06-27 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_alter_user_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(default='user_17abf35e-d4aa-4281-9e88-51f31de8884e', max_length=150, unique=True),
        ),
    ]
