# Generated by Django 4.2.2 on 2023-06-27 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_alter_user_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(default='user_448767b9-2de4-444e-b7c1-8e19ca44f13c', max_length=150, unique=True),
        ),
    ]
