# Generated by Django 4.2.2 on 2023-06-27 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_alter_user_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(default='user_2a4f6efe-c5c9-48b1-8e7d-97e74484f3f7', max_length=150, unique=True),
        ),
    ]
