# Generated by Django 4.2.2 on 2023-06-27 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_alter_user_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(default='user_adf6d059-fbb3-44f0-8bc9-9be472dd06b7', max_length=150, unique=True),
        ),
    ]
