# Generated by Django 4.2.2 on 2023-06-27 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_alter_user_managers_alter_user_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(default='user_bcb3ff10-bab0-4ee2-86d6-5b1ce07aa233', max_length=150, unique=True),
        ),
    ]
