# Generated by Django 4.2.2 on 2023-06-27 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_alter_user_managers_alter_user_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(default='user_a62e03e9-5c4f-4cc6-b8e9-dd926ef57873', max_length=150, unique=True),
        ),
    ]
