# Generated by Django 4.2.2 on 2023-07-06 10:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0017_user_follows'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='follows',
            new_name='followers',
        ),
    ]
