# Generated by Django 4.2.2 on 2023-06-30 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='upvote',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
