# Generated by Django 4.2.2 on 2023-07-03 08:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0002_alter_ticket_upvote'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='picture',
        ),
    ]
