# Generated by Django 4.2.2 on 2023-07-07 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0003_remove_review_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='body',
            field=models.CharField(blank=True, max_length=1000, verbose_name='Commentaire'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='headline',
            field=models.CharField(max_length=120, verbose_name='Titre'),
        ),
    ]
