# Generated by Django 4.2.2 on 2023-07-10 04:49

from django.db import migrations
import django_resized.forms


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0007_alter_review_ticket'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='picture',
            field=django_resized.forms.ResizedImageField(blank=True, crop=None, force_format=None, keep_meta=True, quality=-1, scale=None, size=[500, 300], upload_to='', verbose_name='Image'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='picture',
            field=django_resized.forms.ResizedImageField(blank=True, crop=None, force_format=None, keep_meta=True, quality=-1, scale=None, size=[500, 300], upload_to='', verbose_name="Image de l'article"),
        ),
    ]
