# Generated by Django 4.2.2 on 2023-07-11 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0008_alter_review_picture_alter_ticket_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='review_posted',
            field=models.BooleanField(default=False),
        ),
    ]
